# CI de Nível 01 - Disparo Manual através de clique

stages:
  - test

e2e-tests:
  stage: test
  image: mcr.microsoft.com/playwright:v1.44.0-jammy
  before_script:
    - yarn
    - yarn playwright install
  script:
    - yarn run e2e
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - reports/
    expire_in: 1 week
  when: manual
